exp: TextClassification

mode:
    - train

models: 
      hf_text_classification_model:
          - roberta-uncased

trainfpath: Mistica-SpanishProDrop/train_data.tsv
validfpath: Mistica-SpanishProDrop/valid_data.tsv
modelfpath: Mistica-SpanishProDrop/LMs/RoBERTuito_test

numLabels: 3

loadPretrained: False

samplePercent: 5